config/routes.rb
Rails.application.routes.draw do
  resources :spaces, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:create]
  end

  resources :bookings, except: [:new, :create, :index] do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:owner]
  resource :dashboard, only: [:show]

  get "/spaces/:space_id/bookings/:id/receipt" => "bookings#receipt", as: "receipt"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :space
  belongs_to :user
  has_many :reviews

  validates :start_date, :end_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :comment, presence: true
  # validates :rating, numericality: true, presence: true
end

app/models/space.rb
class Space < ApplicationRecord
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  serialize :amenities
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings


  AMENITIES = ["lock", "monitor", "desk", "mouse", "keyboard", "mirror", "tea", "coffee", "massage",
               "parking", "snacks", "shower", "hairdryer", "vacuum cleaner", "yoga mats", "balcony", "rooftop",
               "music player", "toaster", "fridge", "peloton"]

  ICONS = {
            lock: 'fas fa-lock',
            monitor: 'fas fa-desktop',
            mouse: 'fas fa-mouse',
            keyboard: 'fas fa-keyboard',
            tea: 'fas fa-mug-hot',
            parking: 'fas fa-parking',
            shower: 'fas fa-shower',
            snacks: 'fas fa-cookie-bite',
            music: 'fab fa-napster',
            massage: 'fas fa-spa',
            peloton: 'fas fa-biking',
            toaster: 'fas fa-bread-slice',
            coffee: 'fas fa-coffee'
          }

  validates :address, :description, :name, presence: true
  validates :price, numericality: true, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_address_and_wrokspace_type,
    against: [ :address, :workspace_type ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # validates :first_name, :last_name, :occupation, presence: true

  has_many :bookings
  has_many :spaces

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :occupation])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
  end

  def new
    @space = Space.find(params[:space_id])
    @booking = Booking.new
  end

  def create
    @space = Space.find(params[:space_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.space = @space
    if @booking.save
      redirect_to receipt_path(@space, @booking), notice: "Congratulations for booking #{@space.name}"
    else
      render :new
    end
  end

  def destroy
  end

  def edit
  end

  def update
  end

  def receipt
    @space = Space.find(params[:space_id])
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :space_id)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @spaces = current_user.spaces
    @bookings = current_user.bookings
    @review = Review.new
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @space = Space.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    respond_to do |format|
      if @review.save
        format.html { redirect_to space_path(@booking.space) }
        format.json # Follow the classic Rails flow and look for a create.json view
        flash[:alert] = "Thank you for your review"
      else
        format.html { render '/dashboard' }
        format.json # Follow the classic Rails flow and look for a create.json view
        flash[:alert] = "Something went wrong."
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment)
  end
end

app/controllers/spaces_controller.rb
require 'open-uri'
require 'json'

class SpacesController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :set_all_spaces, only: [:index, :show]

  def index
    if params[:query]
      @spaces = Space.search_by_address_and_wrokspace_type(params[:query])
    else
      @spaces = Space.all
    end
  end

  def show
    @space = Space.find(params[:id])
    @user = User.find(@space.user_id)
    @markers = @space.geocode.map do
      {
        lat: @space.latitude,
        lng: @space.longitude
      }
    end
    @booking = Booking.new
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    @space.amenities = params["amenities"]["amenities"].join(" ")
    @space.save!
    if @space.save
      redirect_to space_path(@space)
    else
      render :new
    end
  end

  def destroy
    @space = Space.find(params[:id])
    @space.destroy
    redirect_to dashboard_path, notice: 'Space was successfully deleted!'
  end

  private

  def space_params
    params.require(:space).permit(:name, :description, :workspace_type, :price,
                                  :address, photos: [])
  end

  def set_all_spaces
    @spaces = Space.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
  end

  def owner
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_review.html.erb
<p id="review-<%= review.id %>"><%= review.content %></p>

app/views/bookings/create.html.erb
<h1>Receipt</h1>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/receipt.html.erb
<h1>Hello this is your receipt for: <%= @space.name %></h1>


<% total_days = @booking.end_date - @booking.start_date %>
<p>Price per day: <strong><%= @space.price %></strong> €</p>
<p>Number of days staying: <strong><%= total_days.to_i %></strong> days</p>
<% @booking.total_price = @space.price * total_days %>
<p>Total price of stay: <strong><%= @booking.total_price %></strong> €</p>

<%= link_to "<< Back to Spaces", spaces_path(), class: "btn btn-primary" %>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/dashboards/show.html.erb
<div class="card p-4 " id="dashboard-card">
  <div class="container ">
    <div class=" pl-5 d-flex bd-highlight mb-3 ">
      <div class="mr-auto p-2 bd-highlight">
        <div class="d-flex">
          <div class="p-2 bd-highlight"><img class="avatar-large flex-column dropdown-toggle"
               id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true"
               aria-expanded="false" src="https://lh3.googleusercontent.com/qt6HS-xCVRYnGGwtEQxEDEyZ61JJAokfVG_EiceGyv6OGBUWlqSqvcrmblb5RWXwCX5SCoPH9KJB9uSUgpxxpsemMSntV7Gg_LXc=w600" />
          </div>
        </div>
          <div class="row">
            <%= link_to "List your place", new_space_path(), class: " card-button btn btn-ghost margin-left=30px " %>
          </div>
        </div>
          <div class="pt-3 pr-5">
            <h1><%= current_user.first_name %> <%= current_user.last_name[0] %>.</h1>

            <h4>First Name: <%= current_user.first_name %></h2>
            <h4>Last name: <%= current_user.last_name %></h2>
            <h4>Occupation: <%= current_user.occupation %></h2>
            <h4>Email: <%= current_user.email %></h2>
          </div>
    </div>
  </div>
</div>

<div class="card" id="personal-card">
    <nav>
      <div class="nav nav-tabs " id="nav-tab" role="tablist">
        <a class="nav-link active navs123" id="nav-home-tab" data-toggle="tab" href="#nav-bookings" role="tab" aria-controls="nav-home" aria-selected="true">Rented places</a>
        <a class="nav-link navs123" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">My places</a>
      </div>
    </nav>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-bookings" role="tabpanel" aria-labelledby="nav-home-tab">
    <table style="width:100% ">
        <thead>
          <tr>
            <td>Status</td>
            <td>Start date</td>
            <td>End date</td>
            <td>Total price</td>
          </tr>

        </thead>

        <% @bookings.each do |booking| %>
            <tr>
              <% date_difference = Date.today - booking.start_date %>
              <td><% if date_difference.to_i < 0  %>
                    <%= booking.status= "Pending"%>
                  <% else %>
                    <%= booking.status="Confirmed" %>
                  <% end %>
              </td>
              <td><%= booking.start_date.strftime('%d-%m-%Y') %></td>
              <td><%= booking.end_date.strftime('%d-%m-%Y') %></td>
              <td><%= booking.space.price * (booking.end_date-booking.start_date) %>€</td>
              <td><button id="review-button" type="button" class="btn" data-toggle="modal" data-target="#exampleModal"
                data-whatever="@fat">Leave a Review</button></td>
              <%= render "reviews/form", booking: booking %>

            </tr>
        <% end %>

      </table>

    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <table style="width:100%" >
        <thead>
          <tr>
            <td>Place</td>
            <td>Location</td>
            <td>Price</td>
            <td></td>
            <td></td>
          </tr>

        </thead>

        <div>
          <% @spaces.each do |space| %>
              <tr>
                <td><%= space.name %></td>
                <td><%= space.address %></td>
                <td><%= space.price %></td>
                <td><%= link_to "X Delete", space_path(space), method: :delete, data: { confirm: "Are you sure you want to delete this?" } %></td>
              </tr>
          <% end %>
        </div>

      </table>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <style>@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
    </style>
  </head>
  <div class=" navbar navbar-expand-sm navbar-light navbar-lewagon d-flex justify-content-between">
    <div  class="toggle">
   <%= link_to root_path, class: "navbar-brand " do %>
     <%= image_tag "homework.png"  %>
   <% end %>
    </div>
   <button class="navbar-toggler" type="button" data-toggle="collapse"
           data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
           aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>

    <div class=" navbar collapse navbar-collapse d-flex justify-content-between" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
     <% if current_user %>
        <!--<li class="nav-item active">Welcome, <%= current_user.first_name %>...</li>
        -->
        <li class="nav-item active" >
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "My account", dashboard_path(), class: "nav-link" %>
        </li>
       <!-- <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://lh3.googleusercontent.com/qt6HS-xCVRYnGGwtEQxEDEyZ61JJAokfVG_EiceGyv6OGBUWlqSqvcrmblb5RWXwCX5SCoPH9KJB9uSUgpxxpsemMSntV7Gg_LXc=w600" />
        </li>
        -->
      <% else %>
        <li style=""class="nav-item active">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item" >
         <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>


  <body style="background-color:#CDD7D6">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>


  <footer>
    <div class="footer d-flex justify-content-center align-items-center">
      <div class="footer-icons d-flex justify-content-between">
        <h1><i class="fab fa-facebook-f icon"></i></a></h1>
        <h1><a href="#"><i class="fab fa-twitter icon"></i></a></h1>
        <h1><a href="#"><i class="fab fa-linkedin-in icon"></i></a></li></h1>
        <h1><a href="#"><i class="fab fa-google-plus-g icon"></i></a></li></h1>
      </div>
  </div>
  </footer>
</html>

app/views/pages/home.html.erb
<div  class="container">
  <div  class="grid-home">
    <div class="big1">
       <%= form_tag spaces_path, method: :get do %>
    <div class="mp34 search-form-control form-group">
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search by city or workspace type...", class: "form-control string required" %>
      <%= button_tag type: 'submit', class: "btn-34 btn btn-primary" do %>
      <i class="fas fa-search"></i>
      <% end %>
    </div>
    <% end %>
    </div>
    <div class="m2"></div>
    <div class="b1g2"></div>
    <div class="m4"></div>
    <div class="f3">
      <h1 class="banner-h1">FROM WHERE WOULD YOU LIKE TO WORK TODAY?</h1>
    </div>
    <div class="d43v">
      <img  style="height: 320px"  src="https://blush.design/api/download?shareUri=XxRzUx4VYQECRNIR&c=Hair_0%7E0f0f0f-0.8%7E9b5120_Skin_0%7Eecafa3-0.8%7Ef6cbc3&w=800&h=800&fm=png" alt="Italian Trulli">
    </div>
  </div>
  <div class="fb23">
    <div class="fb1"></div>
    <div class="fb2 d-flex">
      <div id="triangle">
          <% if current_user %>
            <%= link_to  spaces_path, type: 'submit', class: "" do %>
            <button class="btn-38">Book</button>
              <% end %>
          <% else %>
            <%= link_to  new_user_session_path, type: 'submit', class: "" do %>
            <button class="btn-38">Book</button>
            <% end %>
          <% end %>
      </div>
      <img  class="img-37" src="https://blush.design/api/download?shareUri=P-So76N9u_1H3Rau&c=Hair_0%7E3164cf_Rainbow_0%7Eff89d4_Skin_0%7Eb02d1c&w=800&h=800&fm=png" alt="">
    </div>
  </div>
  <div class="fb23">
    <div >
    </div>
    <div class="fb3 d-flex ">
      <img  class="img-38" src="https://blush.design/api/download?shareUri=sNgscyXxvXfhnv-D&c=Hair_0%7E372310-0.4%7Ead3409_Skin_0%7E673a18-0.4%7Ef4d4b8&w=800&h=800&fm=png" alt="">
      <div id="triangle2">
        <div class=" search-form-control form-group">
        <% if current_user %>
            <%= link_to  new_space_path, type: 'submit', class: "" do %>
            <button class="btn-37">Host</button>
          <% end %>
        <% else %>
          <%= link_to  new_user_session_path, type: 'submit', class: "" do %>
            <button class="btn-37">Host</button>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
    <div class="fb1">
    </div>
  </div>
</div>

app/views/partials/_calender.html.erb
<div class="box-cal" style="width: 45%;height:300px;">
  <%= simple_form_for [@space, @booking], method: "post" do |f| %>
  <div class="form-inputs w-50">
    <%= f.input :start_date, as: :string, label: false, placeholder: "Check-In", input_html: {class: "datepicker"} %>
    <%= f.input :end_date, as: :string, label: false,  placeholder: "Check-Out", input_html: {class: "datepicker"} %>
    <%= f.button :submit, value: "Book Space", class: "button-bookspace" %>
  </div>
  <% end %>
</div>

app/views/partials/_form.html.erb
<div class="conatiner create-form">
  <%= simple_form_for(@space, url: spaces_path, method: :post) do |f| %>
    <div class="form-inputs">
      <div class="row">
        <div class="col-md-6">
          <%= f.input :name, label: false, placeholder: "Space name", class: "rounded" %>
        </div>
        <div class="col-md-6">
          <%= f.input :workspace_type, label: false, placeholder: "Workspace type - please choose one" %>
        </div>
      </div>
      <%= f.input :description, as: :text, label: false, placeholder: "Write a little description" %>
      <%= f.input :price, label: false, placeholder: "price per day (in euros)" %>
      <%= f.input :address, label: false, placeholder: "Please enter the address" %>
      <%= f.input :photos, multiple: true , label: "Upload space photos (please choose 3)" %>
      <div class="d-flex">
        <%= simple_fields_for :amenities do |o| %>
        <%= o.input :amenities, as: :check_boxes, collection: Space::AMENITIES, include_hidden: false, label: 'What amenities you space offer:' %>
        <% end %>
      </div>
      <div class="d-flex justify-content-between">
        <%= f.submit %>
        <p><%= link_to "Not the page i was looking for", spaces_path, class: "back-button" %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/partials/_new_review.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Review</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <%= simple_form_for([ @booking, @review ], url: booking_reviews_path(booking),
                      data: { insert_in_list_target: 'form',
                              action: 'submit->insert-in-list#send' }) do |f| %>
          <%#= simple_form_for [@booking, @review], remote: true, url: booking_reviews_path(booking), method: "POST" do |f|  %>
          <div class="form-group">
            <%= f.text_area :comment, style: "width:90%; border-radius:15px", class: "p-2", placeholder: "Write your review here..." %>
            <%= f.input :rating, collection: (1..10).to_a, label: "Rate your experience" %>
          <%= f.submit "Leave", class: "card-button btn btn-primary align-items-center", style: "  margin: 0 auto" %>
          <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Review</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for([ @booking, @review ], url: booking_reviews_path(booking),
                      data: { insert_in_list_target: 'form',
                              action: 'submit->insert-in-list#send' }) do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, style: "width:90%; border-radius:15px", class: "p-2", placeholder: "Write your review here..." %>
          <%= f.input :rating, collection: (1..10).to_a, label: "Rate your experience" %>
          <%= f.submit "Leave", class: "card-button btn btn-primary align-items-center", style: "  margin: 0 auto" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/spaces/index.html.erb
<div class="container">


  <%# <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.."> %>

  <div id="myBtnContainer" class="d-flex">
    <button class="button-show-all filters active"><%= link_to "Show All", controller: "spaces", action: "index" %>
    </button>
    <% @spaces.each do |space| %>
      <button class="button-filter filters"><%= link_to "#{space.workspace_type}", controller: "spaces", action: "index", query: "#{space.workspace_type}"  %>
      </button>
    <% end %>
  </div>
  <div>
    <div class="grid-container">
          <% @spaces.each do |space| %>
            <div class="grid-item">
              <div class="index-card card">
                <div style="background-image: url('<%= cl_image_path space.photos.first.key, crop: :fill %>'); background-size: cover; margin: 5px; height: 350px; width: auto; border-radius: 5px; background-position: center; opacity: 1" class="card-body-image"></div>
                <div class="d-flex justify-content-between">
                  <div>
                    <div class="space-title">
                      <h3><strong><%= space.name %></strong></h3>
                    </div>
                    <div>
                      <p><%= space.address %></p>
                      <p>Rating: <%= space.rating %></p>
                      <p>Price: <%= space.price %>€</p>
                    </div>
                  </div>
                  <div class="user-avatar align-content-center"><img src="https://www.allthetests.com/quiz22/picture/pic_1171831236_1.png?1592828498" alt="">
                  </div>
                </div>
                <div class="d-flex justify-content-center">
                  <%= link_to space_path(space) do %>
                    <div class="card-button">
                      <%= "Rent" %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
        <% end %>
      </div>
  </div>
</div>

app/views/spaces/new.html.erb
<div class="container">
  <h1>Create new Listing:</h1>
   <%= render partial: "partials/form" %>
  <br>
  <br>
</div>

app/views/spaces/show.html.erb
<div class="d-flex justify-content-between space-title-show">
  <h1 class="container"><%= @space.name %></h1>
</div>
<div class="container">
  <div class="space-overview-top">
    <p class="space-description"><em><%= @space.description %><em></p>
    <div class="container">
      <div class="row d-flex justify-content-center">
        <div class="col-md-12 carousel-image">
          <div id="myCarousel" class="carousel slide" data-ride="carousel" text-align="center">
            <div class="carousel-inner">
              <div class="carousel-item active"> <%= image_tag @space.photos.first, class: "img-carrousel" %> </div>
              <div class="carousel-item"> <%= image_tag @space.photos.second, class: "img-carrousel" %> </div>
              <div class="carousel-item"> <%= image_tag @space.photos.last, class: "img-carrousel" %> </div>
            </div>
            <ol class="carousel-indicators list-inline pic-container">
              <li class="list-inline-item active"> <a id="carousel-selector-0" class="selected" data-slide-to="0"
                  data-target="#myCarousel"> <%= image_tag @space.photos.first, class: "img-fluid rounded" %> </a>
              </li>
              <li class="list-inline-item"> <a id="carousel-selector-1" data-slide-to="1" data-target="#myCarousel">
                  <%= image_tag @space.photos.second, class: "img-fluid rounded" %> </a> </li>
              <li class="list-inline-item"> <a id="carousel-selector-2" data-slide-to="2" data-target="#myCarousel">
                  <%= image_tag @space.photos.last, class: "img-fluid rounded" %> </a> </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
    <p>🌟 Rating: <%= @space.rating %></p>
  <div class="space-body">
    <p>For Rent By: <%= @user.email %></p>
  </div>
  <div class="d-flex justify-content-between center-show">
    <div class="box-shadow" id="map" style="width: 45%; height: 300px;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
         <%= render partial: "partials/calender" %>
  </div>
  <div class="show-bottom">
    <div class="container text-center">
      <h4>Amenities:</h4>
        <div class="amenities">
          <ul class="amenities-list">
            <% @space.amenities.split(" ").each do |amenitie| %>
              <li><i class="<%= Space::ICONS[:"#{amenitie}"] %>"></i></li>
            <% end %>
          </ul>
        </div>
    </div>
    <div data-controller="insert-in-list">
      <div data-insert-in-list-target="items reviews">
        <p><%= @space.name %> Reviews:</p>
          <% @space.reviews.each do |review| %>
            <p><%= review.comment %></p>
          <% end %>
      </div>
    </div>
</div>

app/views/spaces/test.html.erb
<%# button %>
<button class="buttonx">Button</button>

<button class="buttonx2">Button</button>

<button class="buttonx3">Button</button>
<%# banner %>

<div class="headerx">
  <h1>Header</h1>
  <p>Sample text</p>
</div>

<div class="headerx2">
  <h1>Header</h1>
  <p>Sample text</p>
</div>

<div class="headerx3">
  <h1>Header</h1>
  <p>Sample text</p>
</div>

<%# card %>

<div class="cardx">
  <div class="card-container">
    <div class="property-image"><img src="https://www.rocketmortgage.com/resources-cmsassets/RocketMortgage.com/Article_Images/Large_Images/TypesOfHomes/types-of-homes-hero.jpg"></div>
    <div class="d-flex justify-content-between">
      <div>
        <h1>Property name</h1>
        <h2>Property price</h2>
        <h3>Property rating</h3>
      </div>
    <div class="user-avatar align-content-center"><img src="https://www.allthetests.com/quiz22/picture/pic_1171831236_1.png?1592828498" alt=""></div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-container">
    <div class="property-image d-flex justify-content-center"><img src="https://www.rocketmortgage.com/resources-cmsassets/RocketMortgage.com/Article_Images/Large_Images/TypesOfHomes/types-of-homes-hero.jpg"></div>
    <div class="d-flex justify-content-between">
      <div>
        <h1>Property name</h1>
        <h2>Property price</h2>
        <h3>Property rating</h3>
      </div>
    <div class="user-avatar align-content-center"><img src="https://www.allthetests.com/quiz22/picture/pic_1171831236_1.png?1592828498" alt=""></div>
    </div>
    <div class="d-flex justify-content-center">
      <button class="card-button">Rent</button>
    </div>
</div>
</div>



<div class="card">
  <div style="background-image: url('https://s30131.pcdn.co/wp-content/uploads/iStock-1226234257-1.jpg'); background-size: cover; background-position: center; opacity: 0.5" class="card-body">
    <h2 class="card-title"><%= link_to space.name, space_path(space) %></h2><br>
    <h4 class="card-subtitle"> <%= space.description %> </h4><br>
    <p class="card-text"> <%= space.address %></p>
    <p> Available </p>
  </div>
  <div class="card-footer d-flex justify-content-between">
    <p>Space rated: X</p>
    <p> <%= space.price %>€</p>
  </div>
</div>
</div>



<%# navbar %>

app/views/users/owner.html.erb
<h1>Users#owner</h1>
<p>Find me in app/views/users/owner.html.erb</p>